apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: phone-pan-1
servers: 1
agents: 4
network: dt-phone-pan-1
subnet: 172.30.14.0/24
options:
  k3d:
    wait: true
    timeout: 180s
  k3s:
    extraArgs:
      - arg: --cluster-cidr=10.14.0.0/16
        nodeFilters:
          - server:*
      - arg: --service-cidr=10.114.0.0/16
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: false
