apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: prosumer-mining
servers: 1
agents: 4
network: dt-prosumer-mining
subnet: 172.30.11.0/24
options:
  k3d:
    wait: true
    timeout: 180s
  k3s:
    extraArgs:
      - arg: --cluster-cidr=10.11.0.0/16
        nodeFilters:
          - server:*
      - arg: --service-cidr=10.111.0.0/16
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: false
